### PR TITLE
New API: exe, @ffmpeg_env, ffmpeg_exe, ffprobe_exe

### PR DESCRIPTION
**Pull request by asinghvi17**
macro ffmpeg(args)
    return quote
        withenv(FFMPEG.execenv) do
            $(args)
        end
    end
end

### CODE REVIEW

**Comment by asinghvi17** [comment]
Have tested locally, so I'm pretty sure this branch works.  @ianshmean @SimonDanisch any feedback?

**Comment by IanButterworth** [comment]
How about a slightly shorter set of macros:
```
@ffmpeg `-version`
```
```
@ffprobe `-version`
```

I guess it would be good to accept both command strings and strings

**Comment by IanButterworth** [comment]
Also, in the past, ffmpeg output has changed to different std's so VideoIO uses:

```julia
function collectexecoutput(exec::Cmd)
    out = Pipe(); err = Pipe()
    p = Base.open(pipeline(ignorestatus(exec), stdout=out, stderr=err))
    close(out.in); close(err.in)
    err_s = readlines(err); out_s = readlines(out)
    return (length(out_s) > length(err_s)) ? out_s : err_s
end
```
https://github.com/JuliaIO/VideoIO.jl/blob/38131d779e191e72ed9638e1f7053b901f57e087/src/util.jl#L31-L37

Maybe that's worth incorporating into the macros?

**Comment by asinghvi17** [comment]
Could we do `exe(args...; command = FFMPEG.ffmpeg)` instead, to leave the macro scene more "pure"?  We could then alias `ffmpeg(args...)` to `exe(args...; command = FFMPEG.ffmpeg)` and `ffprobe(args...)` to `exe(args...; command = FFMPEG.ffprobe)` in a similar way to Homebrew - and have special casing in `exe` for `Cmd` literals versus strings.

**Comment by IanButterworth** [comment]
I like that

**Comment by IanButterworth** [comment]
Wait, that would mean the `ffmpeg` namespace would need to be both a variable and function..

**Comment by asinghvi17** [comment]
Yeah, just realized that :(.  The macro thing will be an annoying API in my opinion, though...

**Comment by asinghvi17** [comment]
Could do `fmpeg` and `fprobe` instead?  Not the cleanest but it could work for now...or we could just use `exe`.  

Edit: `mpeg` and `probe` are also options.

**Comment by IanButterworth** [comment]
I think dropping an `f` would be confusing. 
How about `ffmpeg_exec()` etc.

**Comment by asinghvi17** [comment]
@ianshmean done...

**Comment by IanButterworth** [comment]
In this new regime, I find the ```@ffmpeg run(`$ffmpeg -version`)``` usage little confusing now.
I'd expect `@ffmpeg` to be limited to the `ffmpeg` executable. Seems redundant given `exe()` and `ffmpeg_exe()` now. Perhaps we drop the macro?

**Comment by asinghvi17** [comment]
Will do!

Edit: Actually, I'll probably rename it to `@ffmpegenv`, since not everything can be done by `run` (like pipelines).

**Pull request merged**
