### PR TITLE
Attempt to move CI for windows to travis & add 32-bit linux

### PR DESCRIPTION
**Pull request by IanButterworth**
Tried to do this at VideoIO with https://github.com/JuliaIO/VideoIO.jl/pull/207 but hit FFMPEG.jl issues, so giving this a go

### CODE REVIEW

**Comment by IanButterworth** [comment]
All windows jobs are failing, with unsatisfied BP products

**Comment by SimonDanisch** [comment]
I really don't get the stack trace:
```
  Building FFMPEG → `C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build.log`
 Resolving package versions...
[ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/Bzip2-v1.0.6-2/Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\Bzip2.v1.0.6.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/ianshmean/ZlibBuilder/releases/download/v1.2.11/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│   caller = ip:0x0
└ @ Core :-1
[ Info: Downloading https://github.com/SimonDanisch/FDKBuilder/releases/download/0.1.6/libfdk.v0.1.6.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\libfdk.v0.1.6.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/SimonDanisch/FribidiBuilder/releases/download/0.14.0/fribidi.v0.14.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\fribidi.v0.14.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaGraphics/FreeTypeBuilder/releases/download/v2.9.1-4/FreeType2.v2.10.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\FreeType2.v2.10.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/LibassBuilder/releases/download/v0.14.0-2/libass.v0.14.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\libass.v0.14.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/LAMEBuilder/releases/download/v3.100.0-2/liblame.v3.100.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\liblame.v3.100.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/OggBuilder/releases/download/v1.3.3-7/Ogg.v1.3.3.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\Ogg.v1.3.3.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/LibVorbisBuilder/releases/download/v1.3.6-2/libvorbis.v1.3.6.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\libvorbis.v1.3.6.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/LibVPXBuilder/releases/download/v1.8.0/LibVPX.v1.8.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\LibVPX.v1.8.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/x264Builder/releases/download/v2019.5.25-static/x264Builder.v2019.5.25.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\x264Builder.v2019.5.25.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/x265Builder/releases/download/v3.0.0-static/x265Builder.v3.0.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\x265Builder.v3.0.0.x86_64-w64-mingw32.tar.gz...
WARNING: replacing module Anon.
[ Info: Downloading https://github.com/JuliaIO/FFMPEGBuilder/releases/download/v4.1.0/FFMPEG.v4.1.0.x86_64-w64-mingw32.tar.gz to C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\usr\downloads\FFMPEG.v4.1.0.x86_64-w64-mingw32.tar.gz...
61.41s$ julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"
LibraryProduct(nothing, ["libavdevice", "avdevice"], :libavdevice, "Prefix(C:\\Users\\travis\\build\\JuliaIO\\FFMPEG.jl\\deps\\usr)") is not satisfied, cannot generate deps.jl!
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] #write_deps_file#156(::Bool, ::typeof(write_deps_file), ::String, ::Array{Product,1}) at C:\Users\travis\.julia\packages\BinaryProvider\TcAwt\src\Products.jl:414
 [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{Product,1}) at .\none:0
 [4] top-level scope at C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build_FFMPEG.v4.1.0.jl:59
 [5] include at .\boot.jl:328 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1094
 [7] include at .\Base.jl:31 [inlined]
 [8] include(::String) at C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build.jl:51
 [9] top-level scope at C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build.jl:52
 [10] include at .\boot.jl:328 [inlined]
 [11] include_relative(::Module, ::String) at .\loading.jl:1094
 [12] include(::Module, ::String) at .\Base.jl:31
 [13] include(::String) at .\client.jl:431
 [14] top-level scope at none:5
in expression starting at C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build_FFMPEG.v4.1.0.jl:59
in expression starting at C:\Users\travis\build\JuliaIO\FFMPEG.jl\deps\build.jl:44
┌ Error: Error building `FFMPEG`: 
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
  Updating registry at `C:\Users\travis\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Testing FFMPEG
 Resolving package versions...
ERROR: LoadError: UndefVarError: ffmpeg not defined
Stacktrace:
 [1] top-level scope at C:\Users\travis\build\JuliaIO\FFMPEG.jl\src\FFMPEG.jl:55
 [2] include at .\boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1094
 [4] include(::Module, ::String) at .\Base.jl:31
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:330 [inlined]
 [7] eval(::Expr) at .\client.jl:432
 [8] top-level scope at .\none:3
in expression starting at C:\Users\travis\build\JuliaIO\FFMPEG.jl\src\FFMPEG.jl:55
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\travis\.julia\compiled\v1.2\FFMPEG\TGvga.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] include(::String) at .\client.jl:431
 [10] top-level scope at none:5
in expression starting at C:\Users\travis\build\JuliaIO\FFMPEG.jl\test\runtests.jl:1
The command "julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"" failed and exited with 1 during .
```
Did printing mess up? Or is something not waiting on the build to finish before starting the tests?
But it seems like it already starts tests:
```
$ julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"
```
And then after that getting an error, which can only come from build:
```
LibraryProduct(nothing, ["libavdevice", "avdevice"], :libavdevice, "Prefix(C:\\Users\\travis\\build\\JuliaIO\\FFMPEG.jl\\deps\\usr)") is not satisfied, cannot generate deps.jl!
```

**Comment by SimonDanisch** [comment]
I also don't get why your appveyor doesn't work :D It just worked smoothly in my PR

**Comment by SimonDanisch** [comment]
Ah, I overlooked, that you actually deleted the appveyor file :D

**Comment by giordano** [comment]
We already discussed about this on Slack, but it's better to point it out also here: Windows installation on Travis is incomplete and FFMPEG cannot work on it, as the system is missing libraries like `avicap32.dll`: https://travis-ci.community/t/any-chance-of-providing-an-environment-with-desktop-experience/1024.  Thus, there is nothing we can do here until this issue is fixed in Travis, if it'll be ever fixed.

Related issue: https://github.com/JuliaIO/FFMPEG.jl/issues/14 (I'd suggest closing it, it's really an upstream error).

**Pull request closed without merging**
